(() => {
const $=id=>document.getElementById(id),video=$('video');let file,url='',dur=0,In=0,Out=0,zoom=60,view=0,clips=[],preview=null;
const fmt=t=>{t=Math.max(0,+t||0);let h=Math.floor(t/3600),m=Math.floor(t%3600/60),s=(t%60).toFixed(1).padStart(4,'0');return h?`${h}:${String(m).padStart(2,'0')}:${s}`:`${m}:${s}`},pct=(v,a,b)=>Math.max(0,Math.min(100,(v-a)/Math.max(.001,b-a)*100));
const toast=m=>{let e=$('toast');e.textContent=m;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1800)};
if(!matchMedia('(display-mode: standalone)').matches&&!navigator.standalone)$('install').style.display='block';$('pickBtn').onclick=()=>$('fileInput').click();$('fileInput').onchange=e=>e.target.files[0]&&load(e.target.files[0]);
function load(f){file=f;if(url)URL.revokeObjectURL(url);url=URL.createObjectURL(f);video.src=url;video.load();$('picker').style.display='none';$('workspace').style.display='block'}
video.onloadedmetadata=()=>{dur=video.duration||0;In=0;Out=Math.min(dur,30);zoom=Math.min(60,dur||60);view=0;restore();update()};video.ontimeupdate=()=>{if(!dur)return;if(zoom!=='full'&&video.currentTime>view+zoom*.92)view=Math.min(Math.max(0,dur-zoom),video.currentTime-zoom*.2);update();if(preview&&video.currentTime>=preview.end){video.pause();preview=null}};video.onplay=()=>playBtn.textContent='❚❚';video.onpause=()=>playBtn.textContent='▶︎';
playBtn.onclick=()=>video.paused?video.play():video.pause();markIn.onclick=()=>{In=Math.min(video.currentTime,Out-.05);update();toast('In '+fmt(In))};markOut.onclick=()=>{Out=Math.max(video.currentTime,In+.05);update();toast('Out '+fmt(Out))};jumpSel.onclick=()=>playRange(In,Out);addClip.onclick=add;clearAll.onclick=()=>{if(!clips.length||confirm('Remove all clips?')){clips=[];save();render()}};
zoomBtns.onclick=e=>{let b=e.target.closest('button[data-zoom]');if(!b)return;document.querySelectorAll('#zoomBtns button').forEach(x=>x.classList.remove('active'));b.classList.add('active');zoom=b.dataset.zoom==='full'?'full':+b.dataset.zoom;center(video.currentTime);update()};document.querySelectorAll('[data-nudge]').forEach(b=>b.onclick=()=>{let[w,d]=b.dataset.nudge.split(',');d=+d;if(w==='in')In=Math.max(0,Math.min(Out-.05,In+d));else Out=Math.min(dur,Math.max(In+.05,Out+d));update()});
overviewTrack.onpointerdown=e=>{let r=overviewTrack.getBoundingClientRect();video.currentTime=(e.clientX-r.left)/r.width*dur;center(video.currentTime);update()};detailTrack.onpointerdown=e=>{if(e.target.classList.contains('handle'))return;let r=detailTrack.getBoundingClientRect(),[a,b]=range();video.currentTime=a+(e.clientX-r.left)/r.width*(b-a);update()};bind(inHandle,'in');bind(outHandle,'out');
function bind(el,w){el.onpointerdown=e=>{e.preventDefault();el.setPointerCapture(e.pointerId);el.onpointermove=ev=>{let r=detailTrack.getBoundingClientRect(),[a,b]=range(),t=a+(ev.clientX-r.left)/r.width*(b-a);t=Math.max(a,Math.min(b,t));if(w==='in')In=Math.max(0,Math.min(Out-.05,t));else Out=Math.min(dur,Math.max(In+.05,t));video.currentTime=t;update()};el.onpointerup=()=>el.onpointermove=null}}
function range(){if(zoom==='full')return[0,dur];let z=Math.min(+zoom,dur),s=Math.min(Math.max(0,view),Math.max(0,dur-z));return[s,Math.min(dur,s+z)]}function center(t){if(zoom==='full'){view=0;return}let z=Math.min(+zoom,dur);view=Math.min(Math.max(0,dur-z),Math.max(0,t-z/2))}
function update(){if(!dur)return;let n=video.currentTime||0;now.textContent=fmt(n);$('dur').textContent=fmt(dur);hudNow.textContent=fmt(n);hudSel.textContent=fmt(Out-In)+' selected';overviewRange.textContent=`${fmt(In)} — ${fmt(Out)}`;overviewPlay.style.left=pct(n,0,dur)+'%';overviewSel.style.left=pct(In,0,dur)+'%';overviewSel.style.width=(pct(Out,0,dur)-pct(In,0,dur))+'%';let[a,b]=range();overviewWindow.style.left=pct(a,0,dur)+'%';overviewWindow.style.width=(pct(b,0,dur)-pct(a,0,dur))+'%';detailLeft.textContent=fmt(a);detailRight.textContent=fmt(b);detailPlay.style.left=pct(n,a,b)+'%';detailSel.style.left=pct(Math.max(In,a),a,b)+'%';detailSel.style.width=Math.max(0,pct(Math.min(Out,b),a,b)-pct(Math.max(In,a),a,b))+'%';inHandle.style.left=pct(In,a,b)+'%';outHandle.style.left=pct(Out,a,b)+'%';inHandle.style.display=In>=a&&In<=b?'block':'none';outHandle.style.display=Out>=a&&Out<=b?'block':'none'}
function key(){return file?`clipmine:${file.name}:${file.size}:${file.lastModified}`:''}function save(){try{localStorage.setItem(key(),JSON.stringify(clips.map(({id,name,start,end})=>({id,name,start,end}))))}catch{}}function restore(){try{clips=JSON.parse(localStorage.getItem(key())||'[]')}catch{clips=[]}render()}
async function thumb(t){return new Promise(res=>{let v=document.createElement('video');v.src=url;v.muted=true;v.playsInline=true;v.onloadedmetadata=()=>v.currentTime=Math.min(dur,Math.max(0,t));v.onseeked=()=>{let c=document.createElement('canvas');c.width=220;c.height=Math.max(124,Math.round(220*(v.videoHeight||9)/(v.videoWidth||16)));c.getContext('2d').drawImage(v,0,0,c.width,c.height);res(c.toDataURL('image/jpeg',.65));v.remove()};setTimeout(()=>res(''),2200)})}
async function add(){if(Out-In<.1)return toast('Select a longer range');let c={id:crypto.randomUUID?crypto.randomUUID():Date.now()+'',name:`Clip ${clips.length+1}`,start:+In.toFixed(3),end:+Out.toFixed(3),thumb:''};clips.push(c);save();render();c.thumb=await thumb(c.start);render();toast('Clip added — keep watching')}
function esc(s){return String(s).replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}function render(){clipCount.textContent=clips.length?`(${clips.length})`:'';if(!clips.length){clipList.innerHTML='<div class="empty">Your clips will appear here.<br><br>Watch → Mark In → Mark Out → Add Clip.</div>';return}clipList.innerHTML=clips.map(c=>`<article class="clip" data-id="${c.id}"><div class="clipTop">${c.thumb?`<img class="thumb" src="${c.thumb}">`:'<div class="thumb"></div>'}<div class="clipMeta"><input class="clipName" value="${esc(c.name)}"><div class="sub">${fmt(c.start)} → ${fmt(c.end)} · ${fmt(c.end-c.start)}</div></div></div><div class="clipBtns"><button class="tiny" data-a="preview">Preview</button><button class="tiny" data-a="load">Adjust</button><button class="primary exportBtn" data-a="export">Export MP4</button><button class="danger" data-a="delete">Delete</button></div></article>`).join('');document.querySelectorAll('.clip').forEach(el=>{let c=clips.find(x=>x.id===el.dataset.id);el.querySelector('.clipName').onchange=e=>{c.name=e.target.value.trim()||c.name;save()};el.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>action(c,b.dataset.a))})}
function action(c,a){if(a==='preview')return show(c);if(a==='load'){In=c.start;Out=c.end;video.currentTime=In;center(In);update();scrollTo({top:0,behavior:'smooth'});return}if(a==='delete'){clips=clips.filter(x=>x.id!==c.id);save();render();return}if(a==='export')window.ClipExporter.export(video,c,toast)}function playRange(s,e){preview={end:e};video.currentTime=s;video.play()}function show(c){sheetTitle.textContent=c.name;sheetInfo.textContent=`${fmt(c.start)} → ${fmt(c.end)} · ${fmt(c.end-c.start)}`;previewVideo.src=url;previewVideo.currentTime=c.start;sheet.classList.add('open');let h=()=>{if(previewVideo.currentTime>=c.end){previewVideo.pause();previewVideo.removeEventListener('timeupdate',h)}};previewVideo.addEventListener('timeupdate',h);previewVideo.play()}closeSheet.onclick=()=>{previewVideo.pause();sheet.classList.remove('open')};sheet.onclick=e=>e.target===sheet&&closeSheet.click();
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
})();